spring.application.name=GiftServiceAuth
spring.datasource.url=jdbc:postgresql://localhost:5432/gift_curse_db
spring.datasource.username=GiftServiceAdm
spring.datasource.password=giftadm
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.platform=postgresql
#spring.jpa.properties.hibernate.format_sql=true
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9000/.well-known/openid-configuration
app.secretKey=703ab371-f2f2-4747-ba40-4cdb004f8514
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
